# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: "pre-release"

on:
  push:
    branches:
      - master
          
jobs:
  bump_version:
    name: "Bump version"
    runs-on: "ubuntu-latest"
    outputs: 
      new_tag: ${{ steps.bump_version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

  release:
    name: "Make new release"
    runs-on: "ubuntu-latest"
    needs: bump_version
    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Package app
        # For some reason, we need to add the execution rights to the mvnw executable first.
        run: chmod +x mvnw && ./mvnw -Pprod -DskipTests package
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ needs.bump_version.outputs.new_tag }}"
          prerelease: true
          title: "Production build"
          files: |
            LICENSE.txt
            target/*.jar
